version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    ports:
      - "80:80"  # Mapear a porta do container para a máquina local
    depends_on:
      - backend
    env_file:
      - .env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:1234@postgres:5432/shopper?schema=public
    env_file:
      - .env
    volumes:
      - ./backend:/usr/src/app
    networks:
      - app-network

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: shopper
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
